---
title: "Clustering Methods"
author: "Manuri Alwis, Jade Thai, Jennifer Rink, Kayla Katakis, and Kylie Maeda"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# **K-means clustering**

K-means clustering is an unsupervised machine learning algorithm. Among unsupervised machine learning algorithms, it is one of the simplest and most popular. These algorithms usually make inferences from data by only looking at the independent variables and not at the dependent variable, also known as the outcome. The objective of k-means is to group similar data points together (into clusters) and find underlying patterns. In order to do so, this algorithm looks for a fixed number of clusters in the data. The \"k\" in k-means refers to the number of clusters. You will define the target number k, which represents the number of centroids you want in the data. The centroid is the center of the cluster. Every data point is assigned to a cluster through reducing the in-cluster sum of squares. Basically, the k-means algorithm finds k centroids and assigns each data point the nearest cluster, while keeping the centroids as small as possible. The \"means\" in k-means refers to averaging of the data.
